
services:
  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:123865@postgres_auth:5432/users1
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    command: sh -c "npx prisma migrate dev --name init && npm run start:dev"
    depends_on:
      - rabbitmq
      - postgres_auth
    restart: always

  postgres_auth:
    container_name: postgres_auth
    image: postgres:16
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_DB: 'users1'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123865'
    ports:
      - '5433:5432'
    volumes:
      - pgdata_auth:/var/lib/postgresql/data
    restart: always

  project-service:
    container_name: project-service
    build:
      context: ./project-service
      dockerfile: Dockerfile
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:123865@postgres_projects:5432/projects
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    volumes:
      - ./project-service:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    command: sh -c "npx prisma migrate dev --name init && npm run start:dev"
    depends_on:
      - rabbitmq
      - postgres_projects
    restart: always

  postgres_projects:
    container_name: postgres_projects
    image: postgres:16
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_DB: 'projects'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123865'
    ports:
      - '5434:5432'
    volumes:
      - pgdata_project:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'dj_pro98@mail.ru'
      PGADMIN_DEFAULT_PASSWORD: '123865'
    ports:
      - '80:80'
    depends_on:
      - postgres_auth
      - postgres_projects
    restart: always

volumes:
  pgdata_auth:
  pgdata_project:
